#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# EverLight v2.0 — Build Script
# Automatically compiles the tweak into a .deb package
# Compatible with Sideloadly
# ═══════════════════════════════════════════════════════════════════════════════

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${PURPLE}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${PURPLE}║           EverLight v2.0 — Build System                        ║${NC}"
echo -e "${PURPLE}║           Enhanced Animal Company Mod Menu                     ║${NC}"
echo -e "${PURPLE}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check if running on macOS
if [[ "$OSTYPE" != "darwin"* ]]; then
    echo -e "${YELLOW}⚠️  Warning: Not running on macOS. Building for iOS requires macOS with Xcode.${NC}"
    echo -e "${YELLOW}   Creating source package instead...${NC}"
    CREATE_SOURCE_ONLY=1
fi

# Check for Theos
if [ -z "$THEOS" ]; then
    if [ -d "$HOME/theos" ]; then
        export THEOS="$HOME/theos"
    elif [ -d "/opt/theos" ]; then
        export THEOS="/opt/theos"
    else
        echo -e "${YELLOW}⚠️  THEOS not found. Will create manual package...${NC}"
        CREATE_SOURCE_ONLY=1
    fi
fi

if [ ! -z "$THEOS" ]; then
    echo -e "${GREEN}✓ THEOS found at: $THEOS${NC}"
fi

# Create output directory
mkdir -p packages
mkdir -p obj

echo ""
echo -e "${CYAN}📦 Building EverLight v2.0...${NC}"
echo ""

# Function to create manual deb package
create_manual_deb() {
    echo -e "${CYAN}🔨 Creating manual .deb package...${NC}"
    
    # Create directory structure
    BUILD_DIR=".build_deb"
    rm -rf "$BUILD_DIR"
    mkdir -p "$BUILD_DIR/DEBIAN"
    mkdir -p "$BUILD_DIR/Library/MobileSubstrate/DynamicLibraries"
    mkdir -p "$BUILD_DIR/var/mobile/Documents/EverLight"
    
    # Copy control file
    cp control "$BUILD_DIR/DEBIAN/"
    
    # Copy plist
    cp EverLight.plist "$BUILD_DIR/Library/MobileSubstrate/DynamicLibraries/"
    
    # Create postinst script with proper permissions
    printf '%s\n' '#!/bin/bash' 'echo "EverLight v2.0 Installed Successfully!"' 'echo "Features: 10-Attempt Spawning, OP Tab, RPC Functions"' 'echo "Compatible with Sideloadly"' 'exit 0' > "$BUILD_DIR/DEBIAN/postinst"
    chmod 0755 "$BUILD_DIR/DEBIAN/postinst"
    
    # Create prerm script with proper permissions
    printf '%s\n' '#!/bin/bash' 'echo "Removing EverLight..."' 'exit 0' > "$BUILD_DIR/DEBIAN/prerm"
    chmod 0755 "$BUILD_DIR/DEBIAN/prerm"
    
    # Create preinst script with proper permissions
    printf '%s\n' '#!/bin/bash' 'echo "Installing EverLight v2.0..."' 'exit 0' > "$BUILD_DIR/DEBIAN/preinst"
    chmod 0755 "$BUILD_DIR/DEBIAN/preinst"
    
    # Create a placeholder dylib (since we can't compile without Xcode)
    cat > "$BUILD_DIR/Library/MobileSubstrate/DynamicLibraries/EverLight.dylib" << 'EOF'
# This is a placeholder. The actual compiled dylib will be generated by Theos.
# To compile:
# 1. Install Theos on macOS
# 2. Run: make package
EOF
    
    # Build the deb
    DEB_NAME="com.everlight.tweak_2.0.0_iphoneos-arm.deb"
    
    if command -v dpkg-deb &> /dev/null; then
        dpkg-deb --build "$BUILD_DIR" "packages/$DEB_NAME"
        echo -e "${GREEN}✓ Created: packages/$DEB_NAME${NC}"
    else
        echo -e "${YELLOW}⚠️  dpkg-deb not found. Creating tar.gz instead...${NC}"
        tar -czf "packages/EverLight-v2.0-source.tar.gz" -C "$BUILD_DIR" .
        echo -e "${GREEN}✓ Created: packages/EverLight-v2.0-source.tar.gz${NC}"
    fi
    
    # Cleanup
    rm -rf "$BUILD_DIR"
}

# Try to build with Theos if available
if [ -z "$CREATE_SOURCE_ONLY" ] && [ ! -z "$THEOS" ]; then
    echo -e "${CYAN}🔨 Attempting to build with Theos...${NC}"
    
    if make clean package FINALPACKAGE=1 2>&1; then
        echo -e "${GREEN}✓ Build successful!${NC}"
        
        # Move the generated deb to packages folder
        if ls packages/*.deb 1> /dev/null 2>&1; then
            echo -e "${GREEN}✓ Package created in packages/ folder${NC}"
        fi
    else
        echo -e "${YELLOW}⚠️  Theos build failed. Creating manual package...${NC}"
        create_manual_deb
    fi
else
    create_manual_deb
fi

# Create source zip
echo ""
echo -e "${CYAN}📁 Creating source archive...${NC}"
zip -r "packages/EverLight-v2.0-source.zip" . -x "packages/*" -x ".git/*" -x "obj/*" -x ".theos/*" 2>/dev/null || true

echo ""
echo -e "${PURPLE}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${PURPLE}║                      BUILD COMPLETE!                           ║${NC}"
echo -e "${PURPLE}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${GREEN}📦 Output files:${NC}"
ls -la packages/ 2>/dev/null || echo "  (Check packages folder)"
echo ""
echo -e "${CYAN}📋 Installation Instructions:${NC}"
echo -e "  1. For jailbroken devices: Install .deb via Filza or dpkg"
echo -e "  2. For Sideloadly: Inject dylib into IPA before sideloading"
echo -e "  3. Source code available in packages/EverLight-v2.0-source.zip"
echo ""
echo -e "${YELLOW}⚠️  Note: To fully compile the dylib, you need:${NC}"
echo -e "     • macOS with Xcode installed"
echo -e "     • Theos framework (https://github.com/theos/theos)"
echo -e "     • iOS SDK"
echo ""
echo -e "${GREEN}✨ EverLight v2.0 — Built with ❤️${NC}"
